# Set to true to disable the Grype image scan completely
disabled: false

ignore:


# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
