# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: "GHSA-4hjh-wcwx-xvwj"  # todo: need to fix this
    package:
      name: "axios"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
