# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: GHSA-9965-vmph-33xx
  - vulnerability: GHSA-vghf-hv5q-vc2g
  - vulnerability: GHSA-5j98-mcp5-4vw2
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2026-22184
  - vulnerability: CVE-2025-64718
  - vulnerability: GHSA-34x7-hfp2-rc4v

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
