# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: GHSA-9965-vmph-33xx
  - vulnerability: GHSA-vghf-hv5q-vc2gs

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
