#!/usr/bin/env bash
export MOCKSERVER_ID=mockserver
export SLEEP_FACTOR_IN_SECONDS=5
export DB_ID=mysql
export DBPASS=password

# Admin API
export ACCOUNT_LOOKUP_ADMIN_URI_PREFIX=http
export ACCOUNT_LOOKUP_ADMIN_HOST=localhost
export ACCOUNT_LOOKUP_ADMIN_PORT=4001
export ACCOUNT_LOOKUP_ADMIN_BASE=/

# FSPIOP API
export ACCOUNT_LOOKUP_FSPIOP_URI_PREFIX=http
export ACCOUNT_LOOKUP_FSPIOP_HOST=localhost
export ACCOUNT_LOOKUP_FSPIOP_PORT=4002
export ACCOUNT_LOOKUP_FSPIOP_BASE=/

export PAYEE_PARTICIPANT_LIST=("27713803912")
